name: Renovate
on:
  push:
    branches:
      - 'main'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v37.0.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          DRY_RUN: true
          RENOVATE_ENABLED_MANAGERS: "regex"
