name: Renovate
on:
  push:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@latest
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          DRY_RUN: true
          RENOVATE_ENABLED_MANAGERS: "regex"
